
services:

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus-monitoreo
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alertas.yml:/etc/prometheus/alertas.yml:ro
      - ./prometheus/targets.json:/etc/prometheus/targets.json:ro
      - ./data/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=100y'
      - '--storage.tsdb.retention.size=50GB'
    restart: unless-stopped
    networks:
      - network_docker


  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_VERSION}
    container_name: alertmanager-monitoreo
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--config.expand-env'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    networks:
      - network_docker

networks:
  network_docker:
    external: true
